//! (PKG Phase 1) Virtual environments + local install + the env-completeness
//! check.
//!
//! A pyrst "venv" is NOT an isolated interpreter (pyrst programs compile to
//! self-contained static binaries — there is no runtime). It is an isolated
//! COMPILE-TIME package store the resolver resolves imports against. This module
//! owns:
//!   - `discover_active_env` — the single source of truth for "is an env active,
//!     and where". PYRST_VENV (explicit, set by `source activate` or `--venv`)
//!     wins; otherwise a `.pyrstenv/` is auto-detected by walking CWD→ancestors.
//!     Returns `None` when neither is found — and when it returns `None` the
//!     resolver's behaviour is byte-for-byte what it was before packaging existed.
//!   - `create`/`init`/`list`/`freeze` — the CLI scaffolding commands.
//!   - `install` — LOCAL-PATH install (Phase 1): verify a manifest, copy the
//!     package's `.pyrs` + manifest into the store, recurse its `dependencies`
//!     with a visited set (→ an honest cycle error; diamonds install once), and
//!     write a pinned `pyrst.lock`. No-arg `install` reproduces from the lock.
//!   - `check_env_completeness` — the design §F manifest-coherence gate the driver
//!     runs before codegen.

use std::collections::{BTreeMap, BTreeSet, HashMap, HashSet};
use std::path::{Path, PathBuf};

use crate::diag::{Error, Result};
use crate::manifest::{DepSource, Manifest, MANIFEST_FILE};

/// The conventional env directory name (auto-detected up the ancestor chain).
pub const ENV_DIR_NAME: &str = ".pyrstenv";
/// The env-metadata marker file; its presence is what makes a directory count as
/// a real pyrst env (both for auto-detect and for an explicit `PYRST_VENV`).
pub const ENV_META_FILE: &str = "pyrst-env.yaml";
/// The isolated package store, one `<name>/` subdir per installed package.
pub const PACKAGES_DIR: &str = "packages";
/// The pinned install set.
pub const LOCK_FILE: &str = "pyrst.lock";

const LOCK_HEADER: &str = "# pyrst.lock — generated by `pyrst install`; do not edit by hand.\n";

// ── active-env discovery ────────────────────────────────────────────────────

/// Discover the active env from the process environment + CWD. Thin wrapper over
/// the pure [`discover_env_from`] so the discovery policy is unit-testable without
/// mutating the process-global `PYRST_VENV` / CWD (which would race the resolver's
/// own tests).
pub fn discover_active_env() -> Option<PathBuf> {
    let pyrst_venv = std::env::var_os("PYRST_VENV");
    let cwd = std::env::current_dir().ok()?;
    discover_env_from(pyrst_venv.as_ref().map(PathBuf::from).as_deref(), &cwd)
}

/// Pure discovery policy (§D): an explicit, valid `PYRST_VENV` wins; otherwise
/// walk `cwd`→ancestors for a `.pyrstenv/` env dir; otherwise `None`. A directory
/// counts as an env only if it exists AND holds a `pyrst-env.yaml` marker, so a
/// coincidentally-named directory is never mistaken for an env.
pub fn discover_env_from(pyrst_venv: Option<&Path>, cwd: &Path) -> Option<PathBuf> {
    if let Some(p) = pyrst_venv {
        if !p.as_os_str().is_empty() && is_env_dir(p) {
            return p.canonicalize().ok();
        }
        // Set but invalid → fall through to auto-detect (lenient, non-crashing).
    }
    let mut dir = Some(cwd);
    while let Some(d) = dir {
        let candidate = d.join(ENV_DIR_NAME);
        if is_env_dir(&candidate) {
            return candidate.canonicalize().ok();
        }
        dir = d.parent();
    }
    None
}

/// A directory is a pyrst env iff it exists and contains the `pyrst-env.yaml`
/// marker.
fn is_env_dir(p: &Path) -> bool {
    p.is_dir() && p.join(ENV_META_FILE).is_file()
}

/// Discover the active env or fail with an honest "no active env" error — used by
/// the commands that REQUIRE one (`install`, `list`, `freeze`).
fn require_active_env() -> Result<PathBuf> {
    discover_active_env().ok_or_else(|| {
        Error::Pkg(format!(
            "no active pyrst environment — create one with `pyrst venv` and `source {}/activate`, \
             or set PYRST_VENV / pass --venv <dir>",
            ENV_DIR_NAME
        ))
    })
}

// ── `pyrst venv` ────────────────────────────────────────────────────────────

/// Create the env skeleton (§D): `pyrst-env.yaml`, an empty `packages/`, an empty
/// `pyrst.lock`, and an `activate` shell script. NO timestamps are written
/// anywhere (determinism).
pub fn create(dir: Option<PathBuf>) -> Result<()> {
    let target = dir.unwrap_or_else(|| PathBuf::from(ENV_DIR_NAME));
    if target.exists() {
        return Err(Error::Pkg(format!(
            "cannot create environment: '{}' already exists",
            target.display()
        )));
    }
    std::fs::create_dir_all(target.join(PACKAGES_DIR))?;
    // Env metadata: the pyrst version that created it. `created-at` is deliberately
    // OMITTED so an env is byte-reproducible.
    std::fs::write(
        target.join(ENV_META_FILE),
        format!("pyrst_version: {}\n", env!("CARGO_PKG_VERSION")),
    )?;
    std::fs::write(target.join(LOCK_FILE), LOCK_HEADER)?;

    let abs = target.canonicalize()?;
    std::fs::write(target.join("activate"), activate_script(&abs))?;

    eprintln!("created pyrst environment: {}", abs.display());
    eprintln!("activate it with:  source {}/activate", target.display());
    Ok(())
}

/// The POSIX `activate` script (source it). Exports `PYRST_VENV=<abs>` and defines
/// a `deactivate` that restores the prior value. Mirrors Python's `venv` activate.
fn activate_script(abs_env: &Path) -> String {
    format!(
        "# pyrst virtual environment — source this file to activate.\n\
         # `deactivate` restores the previous PYRST_VENV (or unsets it).\n\
         deactivate() {{\n\
         \x20   if [ -n \"${{_OLD_PYRST_VENV+x}}\" ]; then\n\
         \x20       PYRST_VENV=\"$_OLD_PYRST_VENV\"; export PYRST_VENV; unset _OLD_PYRST_VENV\n\
         \x20   else\n\
         \x20       unset PYRST_VENV\n\
         \x20   fi\n\
         \x20   unset -f deactivate\n\
         }}\n\
         _OLD_PYRST_VENV=\"${{PYRST_VENV:-}}\"\n\
         PYRST_VENV=\"{}\"\n\
         export PYRST_VENV\n",
        abs_env.display()
    )
}

// ── `pyrst init` ────────────────────────────────────────────────────────────

/// Scaffold a `pyrst.yaml` for the current directory (make it a package). Refuses
/// to overwrite an existing manifest.
pub fn init() -> Result<()> {
    let cwd = std::env::current_dir()?;
    let path = cwd.join(MANIFEST_FILE);
    if path.exists() {
        return Err(Error::Pkg(format!("{} already exists", path.display())));
    }
    let raw = cwd.file_name().and_then(|s| s.to_str()).unwrap_or("package");
    let name = sanitize_name(raw);
    let content = format!(
        "name: {}\nversion: 0.1.0\npackage_root: .\ndependencies: []\n",
        name
    );
    std::fs::write(&path, content)?;
    eprintln!("scaffolded {}", path.display());
    Ok(())
}

/// Map an arbitrary directory name to a valid package name (`[a-z0-9_-]+`),
/// lowercasing and replacing every other character with `-`; empty → `package`.
fn sanitize_name(raw: &str) -> String {
    let mapped: String = raw
        .chars()
        .map(|c| {
            let c = c.to_ascii_lowercase();
            if c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_' || c == '-' {
                c
            } else {
                '-'
            }
        })
        .collect();
    if mapped.is_empty() {
        "package".to_string()
    } else {
        mapped
    }
}

// ── `pyrst list` / `pyrst freeze` ───────────────────────────────────────────

/// List packages installed in the active env, one `name@version` per line
/// (stdout), sorted by name.
pub fn list() -> Result<()> {
    let env = require_active_env()?;
    let store = env.join(PACKAGES_DIR);
    let mut names: Vec<String> = Vec::new();
    if store.is_dir() {
        for entry in std::fs::read_dir(&store)?.flatten() {
            if entry.path().is_dir() {
                names.push(entry.file_name().to_string_lossy().into_owned());
            }
        }
    }
    names.sort();
    if names.is_empty() {
        eprintln!("no packages installed in {}", env.display());
        return Ok(());
    }
    for n in names {
        match Manifest::load(&store.join(&n)) {
            Ok(m) => println!("{}@{}", m.name, m.version),
            // A store subdir without a readable manifest is surfaced honestly
            // rather than silently dropped.
            Err(_) => println!("{}@?", n),
        }
    }
    Ok(())
}

/// Print the pinned lock set verbatim (stdout) — for sharing / CI.
pub fn freeze() -> Result<()> {
    let env = require_active_env()?;
    let text = std::fs::read_to_string(env.join(LOCK_FILE)).unwrap_or_default();
    print!("{}", text);
    Ok(())
}

// ── lockfile ────────────────────────────────────────────────────────────────

/// One pinned package in `pyrst.lock`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LockEntry {
    pub name: String,
    pub version: String,
    pub source: DepSource,
}

/// Read `<env>/pyrst.lock` into a name→entry map. A missing lock is an empty map.
pub fn read_lock(env: &Path) -> Result<BTreeMap<String, LockEntry>> {
    let path = env.join(LOCK_FILE);
    let text = match std::fs::read_to_string(&path) {
        Ok(t) => t,
        Err(_) => return Ok(BTreeMap::new()),
    };
    let mut map = BTreeMap::new();
    for line in text.lines() {
        let line = line.trim_end();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let fields: Vec<&str> = line.split('\t').collect();
        if fields.len() != 4 {
            return Err(Error::Pkg(format!(
                "{}: malformed lock line (expected 4 tab-separated fields): {}",
                path.display(),
                line
            )));
        }
        let source = match fields[2] {
            "path" => DepSource::Path(fields[3].to_string()),
            "git" => DepSource::Git(fields[3].to_string()),
            other => {
                return Err(Error::Pkg(format!(
                    "{}: unknown lock source kind `{}`",
                    path.display(),
                    other
                )))
            }
        };
        map.insert(
            fields[0].to_string(),
            LockEntry {
                name: fields[0].to_string(),
                version: fields[1].to_string(),
                source,
            },
        );
    }
    Ok(map)
}

/// Write the lock deterministically: a fixed header + one tab-separated line per
/// package, SORTED by name (the `BTreeMap` iteration order). No timestamps.
pub fn write_lock(env: &Path, lock: &BTreeMap<String, LockEntry>) -> Result<()> {
    let mut out = String::from(LOCK_HEADER);
    for entry in lock.values() {
        let (kind, value) = match &entry.source {
            DepSource::Path(p) => ("path", p.as_str()),
            DepSource::Git(g) => ("git", g.as_str()),
        };
        out.push_str(&format!(
            "{}\t{}\t{}\t{}\n",
            entry.name, entry.version, kind, value
        ));
    }
    std::fs::write(env.join(LOCK_FILE), out)?;
    Ok(())
}

// ── `pyrst install` ─────────────────────────────────────────────────────────

/// Install a local package (and its transitive path-deps) into the active env, or
/// — with no argument — reproduce the env from its `pyrst.lock`.
pub fn install(arg: Option<PathBuf>) -> Result<()> {
    let env = require_active_env()?;
    let count = match arg {
        Some(path) => {
            let canon = path.canonicalize().map_err(|_| {
                Error::Pkg(format!("install path '{}' does not exist", path.display()))
            })?;
            install_into(&env, &canon)?
        }
        None => reproduce_into(&env)?,
    };
    eprintln!("installed {} package(s) into {}", count, env.display());
    Ok(())
}

/// DFS state carried through a single install run.
struct InstallState {
    /// `<env>/packages`.
    store: PathBuf,
    /// The accumulating lock set (seeded from the existing lock so incremental
    /// installs add to the env). Written back at the end.
    lock: BTreeMap<String, LockEntry>,
    /// Packages fully processed THIS run (copied + recursed) — diamond dedup.
    done: HashSet<String>,
    /// Names currently on the DFS stack — cycle detection.
    stack: Vec<String>,
    /// name → canonical source dir seen THIS run — collision detection.
    seen_src: HashMap<String, PathBuf>,
}

/// Install the package rooted at `pkg_dir` (and its deps) into `env`, updating
/// `<env>/pyrst.lock`. Takes `env` EXPLICITLY (no global discovery) so it is
/// directly unit-testable. Returns the number of packages installed this run.
pub fn install_into(env: &Path, pkg_dir: &Path) -> Result<usize> {
    let store = env.join(PACKAGES_DIR);
    std::fs::create_dir_all(&store)?;
    let mut state = InstallState {
        store,
        lock: read_lock(env)?,
        done: HashSet::new(),
        stack: Vec::new(),
        seen_src: HashMap::new(),
    };
    install_dfs(&mut state, pkg_dir, None)?;
    write_lock(env, &state.lock)?;
    Ok(state.done.len())
}

/// Reproduce the env from its lock: install every locked package from its pinned
/// (path) source.
fn reproduce_into(env: &Path) -> Result<usize> {
    let lock = read_lock(env)?;
    if lock.is_empty() {
        return Err(Error::Pkg(format!(
            "nothing to reproduce: {} has no locked packages",
            env.join(LOCK_FILE).display()
        )));
    }
    let store = env.join(PACKAGES_DIR);
    std::fs::create_dir_all(&store)?;
    let mut state = InstallState {
        store,
        lock: lock.clone(),
        done: HashSet::new(),
        stack: Vec::new(),
        seen_src: HashMap::new(),
    };
    for entry in lock.values() {
        match &entry.source {
            DepSource::Path(p) => {
                let dir = PathBuf::from(p).canonicalize().map_err(|_| {
                    Error::Pkg(format!(
                        "locked path '{}' for package `{}` no longer exists",
                        p, entry.name
                    ))
                })?;
                install_dfs(&mut state, &dir, Some(&entry.name))?;
            }
            DepSource::Git(_) => {
                return Err(Error::Pkg(format!(
                    "package `{}` has a git source — reproducing git installs is Phase 2",
                    entry.name
                )))
            }
        }
    }
    write_lock(env, &state.lock)?;
    Ok(state.done.len())
}

/// The install DFS body for one package directory. `pkg_dir` MUST be canonical.
/// `expected_name`, when set, is the dependency name the parent declared — used to
/// catch a manifest whose `name` disagrees with how it was referenced.
fn install_dfs(state: &mut InstallState, pkg_dir: &Path, expected_name: Option<&str>) -> Result<()> {
    let manifest = Manifest::load(pkg_dir)?;
    let name = manifest.name.clone();

    if let Some(exp) = expected_name {
        if exp != name {
            return Err(Error::Pkg(format!(
                "dependency was declared as `{}` but the package at {} is named `{}`",
                exp,
                pkg_dir.display(),
                name
            )));
        }
    }

    // Cycle: the package is already on the current DFS stack.
    if let Some(pos) = state.stack.iter().position(|n| n == &name) {
        let mut cycle: Vec<String> = state.stack[pos..].to_vec();
        cycle.push(name.clone());
        return Err(Error::Pkg(format!(
            "dependency cycle detected: {}",
            cycle.join(" → ")
        )));
    }

    // Diamond: already fully installed this run.
    if state.done.contains(&name) {
        return Ok(());
    }

    // Collision — same name, a DIFFERENT source directory.
    if let Some(prev) = state.seen_src.get(&name) {
        if prev != pkg_dir {
            return Err(collision_err(&name, prev, pkg_dir));
        }
    }
    if let Some(entry) = state.lock.get(&name) {
        if let DepSource::Path(p) = &entry.source {
            if let Ok(prev_canon) = PathBuf::from(p).canonicalize() {
                if prev_canon != pkg_dir {
                    return Err(collision_err(&name, &prev_canon, pkg_dir));
                }
            }
        }
    }

    state.seen_src.insert(name.clone(), pkg_dir.to_path_buf());

    // Copy the package (manifest + its `.pyrs` tree) into the store.
    copy_package(pkg_dir, &state.store.join(&name))?;

    // Pin it in the lock (canonical abs path so a no-arg reproduce is robust).
    state.lock.insert(
        name.clone(),
        LockEntry {
            name: name.clone(),
            version: manifest.version.clone(),
            source: DepSource::Path(pkg_dir.to_string_lossy().into_owned()),
        },
    );

    // Recurse into declared dependencies.
    state.stack.push(name.clone());
    for dep in &manifest.dependencies {
        let dep_dir = match &dep.source {
            DepSource::Path(p) => {
                let joined = pkg_dir.join(p);
                joined.canonicalize().map_err(|_| {
                    Error::Pkg(format!(
                        "package `{}` declares dependency `{}` at path `{}`, which does not exist",
                        name, dep.name, p
                    ))
                })?
            }
            DepSource::Git(url) => {
                return Err(Error::Pkg(format!(
                    "package `{}` declares a git dependency `{}` ({}) — installing from git is Phase 2; \
                     use a `path:` dependency for now",
                    name, dep.name, url
                )))
            }
        };
        install_dfs(state, &dep_dir, Some(&dep.name))?;
    }
    state.stack.pop();
    state.done.insert(name);
    Ok(())
}

fn collision_err(name: &str, prev: &Path, current: &Path) -> Error {
    Error::Pkg(format!(
        "package name collision: `{}` is already installed from {} but is now requested from {} — \
         two different sources cannot share one env name",
        name,
        prev.display(),
        current.display()
    ))
}

/// Copy a package into `dst`: the manifest + every `.pyrs` under `src_root`
/// (recursively, structure-preserving). `dst` is removed first so a re-install is
/// a deterministic fresh copy. Non-`.pyrs` files (READMEs, test oracles, compiled
/// demos) are NOT copied — only the manifest and the importable source. Any extra
/// `.pyrs` that is never imported is inert (the resolver only parses a module when
/// something imports it), so copying the whole `.pyrs` tree is safe and supports
/// nested-module packages.
fn copy_package(src_root: &Path, dst: &Path) -> Result<()> {
    if dst.exists() {
        std::fs::remove_dir_all(dst)?;
    }
    std::fs::create_dir_all(dst)?;
    std::fs::copy(src_root.join(MANIFEST_FILE), dst.join(MANIFEST_FILE)).map_err(|e| {
        Error::Pkg(format!(
            "failed to copy manifest from {}: {}",
            src_root.display(),
            e
        ))
    })?;
    copy_pyrs_tree(src_root, src_root, dst)
}

/// Recursively copy every `*.pyrs` file under `dir`, replicating its path relative
/// to `root` beneath `dst`. Directory entries are visited in sorted order for
/// deterministic behaviour.
fn copy_pyrs_tree(root: &Path, dir: &Path, dst: &Path) -> Result<()> {
    let mut entries: Vec<PathBuf> = std::fs::read_dir(dir)?
        .flatten()
        .map(|e| e.path())
        .collect();
    entries.sort();
    for path in entries {
        if path.is_dir() {
            copy_pyrs_tree(root, &path, dst)?;
        } else if path.extension().and_then(|s| s.to_str()) == Some("pyrs") {
            let rel = path.strip_prefix(root).unwrap_or(&path);
            let target = dst.join(rel);
            if let Some(parent) = target.parent() {
                std::fs::create_dir_all(parent)?;
            }
            std::fs::copy(&path, &target)?;
        }
    }
    Ok(())
}

// ── §F env-completeness gate (driver-side) ──────────────────────────────────

/// From the resolved modules' canonical source paths, collect the set of env
/// PACKAGE names the build actually used — i.e. modules whose source lives under
/// `<env>/packages/<name>/`. Modules from the entry program's own tree or the
/// embedded stdlib are excluded (their paths are not under the store).
pub fn used_env_packages(env: &Path, source_paths: &[&Path]) -> BTreeSet<String> {
    let store = env.join(PACKAGES_DIR);
    let store = store.canonicalize().unwrap_or(store);
    let mut used = BTreeSet::new();
    for sp in source_paths {
        if let Ok(rel) = sp.strip_prefix(&store) {
            if let Some(first) = rel.components().next() {
                used.insert(first.as_os_str().to_string_lossy().into_owned());
            }
        }
    }
    used
}

/// (§F) Confirm the env is COMPLETE for the packages the build uses: every used
/// package's manifest-declared dependencies must ALSO be installed in the store.
/// An incomplete env is an honest error naming exactly what to install, raised
/// BEFORE codegen. (Most missing-package cases are already caught earlier by the
/// resolver's env-aware `PackageNotInstalled`; this adds the manifest-coherence
/// guarantee that the env is self-consistent.)
pub fn check_env_completeness(env: &Path, used: &BTreeSet<String>) -> Result<()> {
    let store = env.join(PACKAGES_DIR);
    for pkg in used {
        let manifest = match Manifest::load(&store.join(pkg)) {
            Ok(m) => m,
            // A used package with no readable manifest in the store should not
            // happen (install copies it); stay lenient rather than fabricate.
            Err(_) => continue,
        };
        for dep in &manifest.dependencies {
            if !store.join(&dep.name).is_dir() {
                return Err(Error::Pkg(format!(
                    "the active environment '{}' is incomplete: package `{}` depends on `{}`, \
                     which is not installed — `pyrst install` it",
                    env.display(),
                    pkg,
                    dep.name
                )));
            }
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A unique temp directory for a test fixture.
    fn temp_dir(tag: &str) -> PathBuf {
        let d = std::env::temp_dir().join(format!(
            "pyrst-venv-test-{}-{}-{}",
            tag,
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        std::fs::create_dir_all(&d).unwrap();
        d
    }

    /// Author a minimal package directory: `pyrst.yaml` + a trivial module.
    fn write_pkg(dir: &Path, name: &str, deps: &[(&str, &str)]) {
        std::fs::create_dir_all(dir).unwrap();
        let mut man = format!("name: {}\nversion: 0.1.0\npackage_root: .\n", name);
        if deps.is_empty() {
            man.push_str("dependencies: []\n");
        } else {
            man.push_str("dependencies:\n");
            for (dname, dpath) in deps {
                man.push_str(&format!("  - name: {}\n    path: {}\n", dname, dpath));
            }
        }
        std::fs::write(dir.join(MANIFEST_FILE), man).unwrap();
        std::fs::write(dir.join(format!("{}.pyrs", name)), "def ping() -> int:\n    return 1\n").unwrap();
    }

    /// A ready-to-use empty env directory (marker + empty store + empty lock).
    fn make_env(dir: &Path) -> PathBuf {
        let env = dir.join(".pyrstenv");
        std::fs::create_dir_all(env.join(PACKAGES_DIR)).unwrap();
        std::fs::write(env.join(ENV_META_FILE), "pyrst_version: test\n").unwrap();
        std::fs::write(env.join(LOCK_FILE), LOCK_HEADER).unwrap();
        env
    }

    /// Discovery: an explicit, valid PYRST_VENV wins over auto-detect.
    #[test]
    fn discovery_explicit_pyrst_venv_wins() {
        let base = temp_dir("disc-explicit");
        let env = make_env(&base);
        // Even with a `.pyrstenv` also present in cwd, the explicit path is used.
        let got = discover_env_from(Some(&env), &base).expect("explicit env resolves");
        assert_eq!(got, env.canonicalize().unwrap());
        let _ = std::fs::remove_dir_all(&base);
    }

    /// Discovery: with no PYRST_VENV, a `.pyrstenv/` is auto-detected by walking
    /// cwd→ancestors (found from a nested subdirectory).
    #[test]
    fn discovery_auto_detect_walks_ancestors() {
        let base = temp_dir("disc-auto");
        let env = make_env(&base);
        let nested = base.join("a").join("b");
        std::fs::create_dir_all(&nested).unwrap();
        let got = discover_env_from(None, &nested).expect("auto-detect finds the ancestor env");
        assert_eq!(got, env.canonicalize().unwrap());
        let _ = std::fs::remove_dir_all(&base);
    }

    /// Discovery: neither PYRST_VENV nor a `.pyrstenv/` → None (the no-env path).
    #[test]
    fn discovery_none_when_absent() {
        let base = temp_dir("disc-none");
        assert!(discover_env_from(None, &base).is_none());
        // A PYRST_VENV pointing at a non-env directory also yields None.
        assert!(discover_env_from(Some(&base), &base).is_none());
        let _ = std::fs::remove_dir_all(&base);
    }

    /// Lockfile round-trip: write then read yields the same map, sorted + pinned.
    #[test]
    fn lockfile_round_trips() {
        let base = temp_dir("lock");
        let env = make_env(&base);
        let mut lock = BTreeMap::new();
        lock.insert(
            "numpyrs".to_string(),
            LockEntry { name: "numpyrs".into(), version: "0.1.0".into(), source: DepSource::Path("/abs/numpyrs".into()) },
        );
        lock.insert(
            "tzdata".to_string(),
            LockEntry { name: "tzdata".into(), version: "0.2.1".into(), source: DepSource::Path("/abs/tzdata".into()) },
        );
        write_lock(&env, &lock).unwrap();
        let back = read_lock(&env).unwrap();
        assert_eq!(back, lock, "lock must round-trip exactly");
        let _ = std::fs::remove_dir_all(&base);
    }

    /// Transitive install + diamond dedup: kodiak→{numpyrs, dateutil, tzdata},
    /// dateutil→tzdata. tzdata (the diamond point) is installed exactly once, and
    /// the lock pins all four.
    #[test]
    fn install_transitive_with_diamond() {
        let base = temp_dir("install-diamond");
        let env = make_env(&base);
        let pkgs = base.join("src");
        write_pkg(&pkgs.join("tzdata"), "tzdata", &[]);
        write_pkg(&pkgs.join("numpyrs"), "numpyrs", &[]);
        write_pkg(&pkgs.join("dateutil"), "dateutil", &[("tzdata", "../tzdata")]);
        write_pkg(
            &pkgs.join("kodiak"),
            "kodiak",
            &[("numpyrs", "../numpyrs"), ("dateutil", "../dateutil"), ("tzdata", "../tzdata")],
        );

        let count = install_into(&env, &pkgs.join("kodiak")).expect("transitive install succeeds");
        assert_eq!(count, 4, "kodiak + its 3 transitive deps install once each (tzdata deduped)");

        let store = env.join(PACKAGES_DIR);
        for p in ["kodiak", "numpyrs", "dateutil", "tzdata"] {
            assert!(store.join(p).join(MANIFEST_FILE).is_file(), "{p} manifest is in the store");
            assert!(store.join(p).join(format!("{p}.pyrs")).is_file(), "{p} module copied");
        }
        let lock = read_lock(&env).unwrap();
        assert_eq!(lock.len(), 4, "lock pins all four packages");

        // Completeness passes for this coherent env.
        let used: BTreeSet<String> = ["kodiak", "numpyrs", "dateutil", "tzdata"].iter().map(|s| s.to_string()).collect();
        check_env_completeness(&env, &used).expect("a fully-installed env is complete");

        let _ = std::fs::remove_dir_all(&base);
    }

    /// Cycle detection: a→b→a is an honest error naming the cycle.
    #[test]
    fn install_cycle_is_honest_error() {
        let base = temp_dir("install-cycle");
        let env = make_env(&base);
        let pkgs = base.join("src");
        write_pkg(&pkgs.join("a"), "a", &[("b", "../b")]);
        write_pkg(&pkgs.join("b"), "b", &[("a", "../a")]);

        let err = install_into(&env, &pkgs.join("a")).unwrap_err().to_string();
        assert!(err.contains("dependency cycle detected"), "got: {err}");
        assert!(err.contains('a') && err.contains('b'), "cycle must name the packages: {err}");
        let _ = std::fs::remove_dir_all(&base);
    }

    /// Completeness: a package that declares a dep which is NOT installed is an
    /// honest incomplete-env error (simulated by installing dateutil→tzdata but
    /// then removing tzdata from the store).
    #[test]
    fn incomplete_env_is_honest_error() {
        let base = temp_dir("incomplete");
        let env = make_env(&base);
        let pkgs = base.join("src");
        write_pkg(&pkgs.join("tzdata"), "tzdata", &[]);
        write_pkg(&pkgs.join("dateutil"), "dateutil", &[("tzdata", "../tzdata")]);
        install_into(&env, &pkgs.join("dateutil")).expect("install");

        // Remove tzdata from the store to make the env incomplete.
        std::fs::remove_dir_all(env.join(PACKAGES_DIR).join("tzdata")).unwrap();

        let used: BTreeSet<String> = ["dateutil"].iter().map(|s| s.to_string()).collect();
        let err = check_env_completeness(&env, &used).unwrap_err().to_string();
        assert!(err.contains("incomplete"), "got: {err}");
        assert!(err.contains("dateutil") && err.contains("tzdata"), "must name the package + missing dep: {err}");
        let _ = std::fs::remove_dir_all(&base);
    }
}
