//! (PKG Phase 1) Virtual environments + local install + the env-completeness
//! check.
//!
//! A pyrst "venv" is NOT an isolated interpreter (pyrst programs compile to
//! self-contained static binaries — there is no runtime). It is an isolated
//! COMPILE-TIME package store the resolver resolves imports against. This module
//! owns:
//!   - `discover_active_env` — the single source of truth for "is an env active,
//!     and where". PYRST_VENV (explicit, set by `source activate` or `--venv`)
//!     wins; otherwise a `.pyrstenv/` is auto-detected by walking CWD→ancestors.
//!     Returns `None` when neither is found — and when it returns `None` the
//!     resolver's behaviour is byte-for-byte what it was before packaging existed.
//!   - `create`/`init`/`list`/`freeze` — the CLI scaffolding commands.
//!   - `install` — LOCAL-PATH install (Phase 1): verify a manifest, copy the
//!     package's `.pyrs` + manifest into the store, recurse its `dependencies`
//!     with a visited set (→ an honest cycle error; diamonds install once), and
//!     write a pinned `pyrst.lock`. No-arg `install` reproduces from the lock.
//!   - `check_env_completeness` — the design §F manifest-coherence gate the driver
//!     runs before codegen.

use std::collections::{BTreeMap, BTreeSet, HashMap, HashSet};
use std::path::{Path, PathBuf};

use crate::diag::{Error, Result};
use crate::fetch;
use crate::manifest::{DepSource, Manifest, MANIFEST_FILE};

/// The conventional env directory name (auto-detected up the ancestor chain).
pub const ENV_DIR_NAME: &str = ".pyrstenv";
/// The env-metadata marker file; its presence is what makes a directory count as
/// a real pyrst env (both for auto-detect and for an explicit `PYRST_VENV`).
pub const ENV_META_FILE: &str = "pyrst-env.yaml";
/// The isolated package store, one `<name>/` subdir per installed package.
pub const PACKAGES_DIR: &str = "packages";
/// The pinned install set.
pub const LOCK_FILE: &str = "pyrst.lock";

const LOCK_HEADER: &str = "# pyrst.lock — generated by `pyrst install`; do not edit by hand.\n";

// ── active-env discovery ────────────────────────────────────────────────────

/// Discover the active env from the process environment + CWD. Thin wrapper over
/// the pure [`discover_env_from`] so the discovery policy is unit-testable without
/// mutating the process-global `PYRST_VENV` / CWD (which would race the resolver's
/// own tests).
///
/// This is the CWD-anchored form used by the env COMMANDS that operate on the
/// current directory (`install`/`list`/`freeze`). The COMPILE path (resolver /
/// LSP / REPL) instead uses [`discover_active_env_for`], which anchors on the root
/// file's directory first (card 587a9dcb).
pub fn discover_active_env() -> Option<PathBuf> {
    let pyrst_venv = std::env::var_os("PYRST_VENV");
    let cwd = std::env::current_dir().ok()?;
    discover_env_from(pyrst_venv.as_ref().map(PathBuf::from).as_deref(), &cwd)
}

/// FILE-ANCHORED discovery (card 587a9dcb) — the single source of truth for "is
/// an env active, and where" ON THE COMPILE PATH (the resolver, the LSP, the
/// REPL). Policy order: an explicit, valid `PYRST_VENV` wins → else walk up from
/// the ANCHOR (the root file's directory) for a `.pyrstenv/` → else walk up from
/// the process CWD (the fallback). Anchoring on the file is what makes `pyrst
/// check /proj/file.pyrs` and the VSCode LSP resolve the project's env regardless
/// of where the process was launched from. The CWD fallback is REQUIRED so the
/// REPL keeps working: its temp file lives in a system temp dir with no
/// `.pyrstenv` ancestor, so it falls back to the CWD = the project the user
/// launched `repl` from. Returns `None` when neither the anchor nor the CWD has a
/// `.pyrstenv` ancestor and `PYRST_VENV` is unset/invalid — and when it returns
/// `None` the resolver's behaviour is byte-for-byte what it was before packaging.
pub fn discover_active_env_for(anchor: &Path) -> Option<PathBuf> {
    let pyrst_venv = std::env::var_os("PYRST_VENV");
    // If the CWD is unreadable, re-use the anchor as the fallback base (the anchor
    // walk already covers it, so the `or_else` is then a harmless no-op).
    let cwd = std::env::current_dir().unwrap_or_else(|_| anchor.to_path_buf());
    discover_env_anchored(pyrst_venv.as_ref().map(PathBuf::from).as_deref(), anchor, &cwd)
}

/// Pure discovery policy (§D): an explicit, valid `PYRST_VENV` wins; otherwise
/// walk `cwd`→ancestors for a `.pyrstenv/` env dir; otherwise `None`. A directory
/// counts as an env only if it exists AND holds a `pyrst-env.yaml` marker, so a
/// coincidentally-named directory is never mistaken for an env.
pub fn discover_env_from(pyrst_venv: Option<&Path>, cwd: &Path) -> Option<PathBuf> {
    if let Some(p) = pyrst_venv {
        if !p.as_os_str().is_empty() && is_env_dir(p) {
            return p.canonicalize().ok();
        }
        // Set but invalid → fall through to auto-detect (lenient, non-crashing).
    }
    walk_for_env(cwd)
}

/// Pure FILE-ANCHORED discovery policy (card 587a9dcb): an explicit, valid
/// `pyrst_venv` wins; otherwise walk `anchor`→ancestors for a `.pyrstenv/`;
/// otherwise walk `cwd`→ancestors (the fallback). Split out from the impure
/// [`discover_active_env_for`] so the policy is unit-testable without mutating the
/// process-global `PYRST_VENV` / CWD.
pub fn discover_env_anchored(pyrst_venv: Option<&Path>, anchor: &Path, cwd: &Path) -> Option<PathBuf> {
    if let Some(p) = pyrst_venv {
        if !p.as_os_str().is_empty() && is_env_dir(p) {
            return p.canonicalize().ok();
        }
        // Set but invalid → fall through to auto-detect (lenient, non-crashing).
    }
    // Anchor (the root file's dir) FIRST, then the process CWD.
    walk_for_env(anchor).or_else(|| walk_for_env(cwd))
}

/// Walk `start`→ancestors for a `.pyrstenv/` env dir, returning its canonical path
/// on the first hit (or `None`). Shared by the CWD-anchored and file-anchored
/// discovery policies so both use one identical ancestor-walk.
///
/// SECURITY (card 587a9dcb): a candidate `<d>/.pyrstenv` is honored only when `<d>`
/// is NOT world-writable. Planting an env requires write access to `<d>`, so a
/// world-writable `<d>` (e.g. the shared OS temp root, mode 1777) makes the env
/// attacker-controllable — any local user could drop `<tmp>/.pyrstenv/packages/
/// <name>/evil.pyrs`, which the compiler would otherwise pull in and run as the
/// victim. This matters because file-anchored discovery walks up from the compiled
/// file's directory, and the REPL's scratch file lives directly in that temp root.
/// Such a candidate is SKIPPED (the walk continues upward); a genuinely user-owned
/// project env (its parent is 0755, not world-writable) is unaffected.
fn walk_for_env(start: &Path) -> Option<PathBuf> {
    let mut dir = Some(start);
    while let Some(d) = dir {
        let candidate = d.join(ENV_DIR_NAME);
        if is_env_dir(&candidate) && !dir_is_world_writable(d) {
            return candidate.canonicalize().ok();
        }
        dir = d.parent();
    }
    None
}

/// True iff `dir` is writable by other users. On unix that is the world-write mode
/// bit (`0o002`) — the property that lets a local attacker plant a `.pyrstenv/`
/// there (see [`walk_for_env`]). Off unix (Windows relies on temp-dir ACLs, which
/// are not world-writable) this is always false, so behavior is unchanged there.
#[cfg(unix)]
fn dir_is_world_writable(dir: &Path) -> bool {
    use std::os::unix::fs::PermissionsExt;
    std::fs::metadata(dir)
        .map(|m| m.permissions().mode() & 0o002 != 0)
        .unwrap_or(false)
}
#[cfg(not(unix))]
fn dir_is_world_writable(_dir: &Path) -> bool {
    false
}

/// A directory is a pyrst env iff it exists and contains the `pyrst-env.yaml`
/// marker.
fn is_env_dir(p: &Path) -> bool {
    p.is_dir() && p.join(ENV_META_FILE).is_file()
}

/// Discover the active env or fail with an honest "no active env" error — used by
/// the commands that REQUIRE one (`install`, `list`, `freeze`).
fn require_active_env() -> Result<PathBuf> {
    discover_active_env().ok_or_else(|| {
        Error::Pkg(format!(
            "no active pyrst environment — create one with `pyrst venv` and `source {}/activate`, \
             or set PYRST_VENV / pass --venv <dir>",
            ENV_DIR_NAME
        ))
    })
}

// ── `pyrst venv` ────────────────────────────────────────────────────────────

/// Create the env skeleton (§D): `pyrst-env.yaml`, an empty `packages/`, an empty
/// `pyrst.lock`, and an `activate` shell script. NO timestamps are written
/// anywhere (determinism).
pub fn create(dir: Option<PathBuf>) -> Result<()> {
    let target = dir.unwrap_or_else(|| PathBuf::from(ENV_DIR_NAME));
    if target.exists() {
        return Err(Error::Pkg(format!(
            "cannot create environment: '{}' already exists",
            target.display()
        )));
    }
    std::fs::create_dir_all(target.join(PACKAGES_DIR))?;
    // Env metadata: the pyrst version that created it. `created-at` is deliberately
    // OMITTED so an env is byte-reproducible.
    std::fs::write(
        target.join(ENV_META_FILE),
        format!("pyrst_version: {}\n", env!("CARGO_PKG_VERSION")),
    )?;
    std::fs::write(target.join(LOCK_FILE), LOCK_HEADER)?;

    let abs = target.canonicalize()?;
    // The absolute path is embedded into line-based shell scripts. A newline or other
    // control character in it can't be safely quoted (it would break the script's line
    // structure); refuse rather than emit a corrupt/injectable activate script. Ordinary
    // metacharacters (`$`, backtick, quotes, `%`) ARE handled — see the *_quote helpers.
    if abs.to_string_lossy().chars().any(|c| c.is_control()) {
        return Err(Error::Pkg(format!(
            "cannot create environment: path contains a control character: {}",
            abs.display()
        )));
    }
    // Ship activation scripts for every shell (Python-venv style) so an env is
    // portable and works on Linux/macOS (bash/zsh), Windows cmd, and PowerShell.
    // Each embeds the local canonical path; the user sources the one for their shell.
    std::fs::write(target.join("activate"), activate_script(&abs))?;
    std::fs::write(target.join("activate.bat"), activate_bat(&abs))?;
    std::fs::write(target.join("deactivate.bat"), deactivate_bat())?;
    std::fs::write(target.join("Activate.ps1"), activate_ps1(&abs))?;

    eprintln!("created pyrst environment: {}", abs.display());
    #[cfg(windows)]
    {
        eprintln!("activate it with:  {}\\activate.bat        (cmd)", target.display());
        eprintln!("               or:  . {}\\Activate.ps1      (PowerShell)", target.display());
    }
    #[cfg(not(windows))]
    eprintln!("activate it with:  source {}/activate", target.display());
    Ok(())
}

/// The prompt label = the env directory's basename (e.g. `.pyrstenv`), like Python's
/// `(venv)`, sanitised to `[A-Za-z0-9._+-]` so it can't inject shell/prompt
/// metacharacters (backticks, `$(...)`, quotes, `)`) into the generated activate
/// scripts — `PS1`/`PROMPT` are re-evaluated on every prompt render. Falls back to a
/// constant if the path has no usable final component.
fn env_label(abs_env: &Path) -> String {
    let raw = abs_env.file_name().and_then(|s| s.to_str()).unwrap_or("pyrstenv");
    let cleaned: String = raw
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() || matches!(c, '.' | '_' | '+' | '-') { c } else { '_' })
        .collect();
    if cleaned.is_empty() { "pyrstenv".to_string() } else { cleaned }
}

/// Single-quote `s` for a POSIX shell (bash/zsh): wrap in `'…'` with each embedded `'`
/// rendered as `'\''`. The result is a fully literal token — no `$`, backtick, or `"`
/// inside is special — which is what closes shell injection via the embedded env path
/// (`PS1` is re-evaluated every render, so an unquoted path could run `$(...)`).
fn posix_squote(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('\'');
    for c in s.chars() {
        if c == '\'' { out.push_str("'\\''"); } else { out.push(c); }
    }
    out.push('\'');
    out
}

/// Single-quote `s` for a PowerShell single-quoted literal: wrap in `'…'` with each
/// embedded `'` doubled. No `$(...)`/`$var` interpolation applies inside such a literal.
fn ps_squote(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('\'');
    for c in s.chars() {
        if c == '\'' { out.push_str("''"); } else { out.push(c); }
    }
    out.push('\'');
    out
}

/// Escape `s` for a cmd `set "VAR=…"` / PATH value: double any `%` so cmd does not
/// expand `%NAME%` at parse time. (`"` cannot occur in a Windows path, and any control
/// character is rejected upstream in `create`, so those need no handling here.)
fn cmd_escape(s: &str) -> String {
    s.replace('%', "%%")
}

/// The POSIX `activate` script (source it). Sets `PYRST_VENV`, prefixes the shell
/// prompt with a green `(label)`, and defines a `deactivate` that restores both. The
/// path is single-quoted (`posix_squote`) so it can't inject. Re-sourcing is idempotent
/// (state saved once, prompt rebuilt from the saved original). Set
/// `PYRST_VENV_DISABLE_PROMPT` before sourcing to skip the prompt change.
fn activate_script(abs_env: &Path) -> String {
    format!(
        "# pyrst virtual environment — source this file to activate.\n\
         # `deactivate` restores the previous PYRST_VENV and prompt.\n\
         deactivate() {{\n\
         \x20   if [ -n \"${{_OLD_PYRST_VENV_SET:-}}\" ]; then\n\
         \x20       PYRST_VENV=\"$_OLD_PYRST_VENV\"; export PYRST_VENV\n\
         \x20   else\n\
         \x20       unset PYRST_VENV\n\
         \x20   fi\n\
         \x20   if [ -n \"${{_PYRST_ACTIVE:-}}\" ]; then PS1=\"$_OLD_PYRST_PS1\"; fi\n\
         \x20   unset _OLD_PYRST_VENV _OLD_PYRST_VENV_SET _OLD_PYRST_PS1 _PYRST_ACTIVE\n\
         \x20   unset -f deactivate\n\
         }}\n\
         if [ -z \"${{_PYRST_ACTIVE:-}}\" ]; then\n\
         \x20   _OLD_PYRST_VENV=\"${{PYRST_VENV-}}\"; _OLD_PYRST_VENV_SET=\"${{PYRST_VENV+1}}\"\n\
         \x20   _OLD_PYRST_PS1=\"${{PS1-}}\"; _PYRST_ACTIVE=1\n\
         fi\n\
         PYRST_VENV={venv}\n\
         export PYRST_VENV\n\
         if [ -z \"${{PYRST_VENV_DISABLE_PROMPT:-}}\" ]; then\n\
         \x20   if [ -n \"${{ZSH_VERSION:-}}\" ]; then\n\
         \x20       PS1=\"%F{{green}}({label})%f ${{_OLD_PYRST_PS1}}\"\n\
         \x20   else\n\
         \x20       PS1=\"\\[\\033[32m\\]({label})\\[\\033[0m\\] ${{_OLD_PYRST_PS1}}\"\n\
         \x20   fi\n\
         fi\n",
        venv = posix_squote(&abs_env.display().to_string()),
        label = env_label(abs_env),
    )
}

/// The Windows `cmd` activation script (`activate.bat`, run it). Sets PYRST_VENV,
/// prefixes the prompt with a green `(label)`, and APPENDS the env dir to PATH so
/// `deactivate` (deactivate.bat) is callable by bare name without shadowing system
/// commands. All prior state is saved ONCE (keyed off `_OLD_PYRST_PATH`) and PATH/PROMPT
/// are rebuilt from the saved originals, so re-running is idempotent and deactivate.bat
/// fully unwinds. The path is `%`-escaped. CRLF for cmd. Set PYRST_VENV_DISABLE_PROMPT
/// to skip the prompt.
fn activate_bat(abs_env: &Path) -> String {
    format!(
        "@echo off\r\n\
         REM pyrst virtual environment (cmd.exe) — run this file to activate.\r\n\
         REM run deactivate to restore the previous PYRST_VENV, PATH, and prompt.\r\n\
         if not defined _OLD_PYRST_PATH set \"_OLD_PYRST_VENV=%PYRST_VENV%\"\r\n\
         if not defined _OLD_PYRST_PATH if not defined PROMPT set \"PROMPT=$P$G\"\r\n\
         if not defined _OLD_PYRST_PATH set \"_OLD_PYRST_PROMPT=%PROMPT%\"\r\n\
         if not defined _OLD_PYRST_PATH set \"_OLD_PYRST_PATH=%PATH%\"\r\n\
         set \"PYRST_VENV={venv}\"\r\n\
         set \"PATH=%_OLD_PYRST_PATH%;{venv}\"\r\n\
         if not defined PYRST_VENV_DISABLE_PROMPT set \"PROMPT=$E[32m({label})$E[0m %_OLD_PYRST_PROMPT%\"\r\n\
         echo pyrst environment active: %PYRST_VENV%\r\n",
        venv = cmd_escape(&abs_env.display().to_string()),
        label = env_label(abs_env),
    )
}

/// The Windows `cmd` deactivation script (`deactivate.bat`, callable as `deactivate`
/// because activate.bat put the env dir on PATH). Restores PYRST_VENV, PATH, and PROMPT
/// from the values activate.bat saved, then clears the `_OLD_PYRST_*` slots (so a later
/// re-activation saves fresh state). CRLF for cmd.
fn deactivate_bat() -> String {
    "@echo off\r\n\
     if defined _OLD_PYRST_VENV (set \"PYRST_VENV=%_OLD_PYRST_VENV%\") else (set \"PYRST_VENV=\")\r\n\
     set \"_OLD_PYRST_VENV=\"\r\n\
     if defined _OLD_PYRST_PATH set \"PATH=%_OLD_PYRST_PATH%\"\r\n\
     set \"_OLD_PYRST_PATH=\"\r\n\
     if defined _OLD_PYRST_PROMPT set \"PROMPT=%_OLD_PYRST_PROMPT%\"\r\n\
     set \"_OLD_PYRST_PROMPT=\"\r\n\
     echo pyrst environment deactivated.\r\n"
        .to_string()
}

/// The PowerShell activation script (`Activate.ps1`; dot-source it: `. .\\Activate.ps1`).
/// Sets $env:PYRST_VENV, prefixes the prompt with a green `(label)`, and defines a
/// `deactivate` restoring both. The path is a single-quoted literal (`ps_squote`) so it
/// can't interpolate. Re-dot-sourcing won't clobber the saved prompt/venv. Set
/// $env:PYRST_VENV_DISABLE_PROMPT to skip the prompt.
fn activate_ps1(abs_env: &Path) -> String {
    format!(
        "# pyrst virtual environment (PowerShell) — dot-source to activate:  . .\\Activate.ps1\n\
         if (-not (Test-Path Env:_OLD_PYRST_VENV)) {{ $env:_OLD_PYRST_VENV = $env:PYRST_VENV }}\n\
         $env:PYRST_VENV = {venv}\n\
         if (-not $env:PYRST_VENV_DISABLE_PROMPT) {{\n\
         \x20   if (-not (Test-Path Function:_pyrst_old_prompt)) {{\n\
         \x20       if (Test-Path Function:prompt) {{ Copy-Item Function:prompt Function:_pyrst_old_prompt }}\n\
         \x20   }}\n\
         \x20   function global:prompt {{\n\
         \x20       Write-Host -NoNewline -ForegroundColor Green \"({label}) \"\n\
         \x20       if (Test-Path Function:_pyrst_old_prompt) {{ _pyrst_old_prompt }} else {{ \"PS $($executionContext.SessionState.Path.CurrentLocation)> \" }}\n\
         \x20   }}\n\
         }}\n\
         function global:deactivate {{\n\
         \x20   $env:PYRST_VENV = $env:_OLD_PYRST_VENV\n\
         \x20   Remove-Item Env:_OLD_PYRST_VENV -ErrorAction SilentlyContinue\n\
         \x20   if (Test-Path Function:_pyrst_old_prompt) {{\n\
         \x20       Copy-Item Function:_pyrst_old_prompt Function:prompt\n\
         \x20       Remove-Item Function:_pyrst_old_prompt\n\
         \x20   }}\n\
         \x20   Remove-Item Function:deactivate -ErrorAction SilentlyContinue\n\
         }}\n\
         Write-Host \"pyrst environment active: $env:PYRST_VENV\"\n",
        venv = ps_squote(&abs_env.display().to_string()),
        label = env_label(abs_env),
    )
}

// ── `pyrst init` ────────────────────────────────────────────────────────────

/// Scaffold a `pyrst.yaml` for the current directory (make it a package). Refuses
/// to overwrite an existing manifest.
pub fn init() -> Result<()> {
    let cwd = std::env::current_dir()?;
    let path = cwd.join(MANIFEST_FILE);
    if path.exists() {
        return Err(Error::Pkg(format!("{} already exists", path.display())));
    }
    let raw = cwd.file_name().and_then(|s| s.to_str()).unwrap_or("package");
    let name = sanitize_name(raw);
    let content = format!(
        "name: {}\nversion: 0.1.0\npackage_root: .\ndependencies: []\n",
        name
    );
    std::fs::write(&path, content)?;
    eprintln!("scaffolded {}", path.display());
    Ok(())
}

/// Map an arbitrary directory name to a valid package name (`[a-z0-9_-]+`),
/// lowercasing and replacing every other character with `-`; empty → `package`.
fn sanitize_name(raw: &str) -> String {
    let mapped: String = raw
        .chars()
        .map(|c| {
            let c = c.to_ascii_lowercase();
            if c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_' || c == '-' {
                c
            } else {
                '-'
            }
        })
        .collect();
    if mapped.is_empty() {
        "package".to_string()
    } else {
        mapped
    }
}

// ── `pyrst list` / `pyrst freeze` ───────────────────────────────────────────

/// List packages installed in the active env, one per line (stdout), sorted by name:
/// `name@version  (git <short-sha>)` for a git-sourced package, `name@version
/// (path <dir>)` for a local one. The source annotation is read from `pyrst.lock`.
pub fn list() -> Result<()> {
    let env = require_active_env()?;
    let store = env.join(PACKAGES_DIR);
    let lock = read_lock(&env).unwrap_or_default();
    let mut names: Vec<String> = Vec::new();
    if store.is_dir() {
        for entry in std::fs::read_dir(&store)?.flatten() {
            if entry.path().is_dir() {
                names.push(entry.file_name().to_string_lossy().into_owned());
            }
        }
    }
    names.sort();
    if names.is_empty() {
        eprintln!("no packages installed in {}", env.display());
        return Ok(());
    }
    for n in &names {
        match Manifest::load(&store.join(n)) {
            Ok(m) => {
                let src = lock.get(&m.name).map(|e| source_label(&e.source)).unwrap_or_default();
                println!("{}@{}{}", m.name, m.version, src);
            }
            // A store subdir without a readable manifest is surfaced honestly
            // rather than silently dropped.
            Err(_) => println!("{}@?", n),
        }
    }
    Ok(())
}

/// The trailing source annotation for `pyrst list`: `  (git <short-sha>)` for a
/// git-pinned package, `  (path <dir>)` for a local one.
fn source_label(s: &LockSource) -> String {
    match s {
        LockSource::Git { commit, .. } => format!("  (git {})", short_sha(commit)),
        LockSource::Path(p) => format!("  (path {})", p),
    }
}

/// Print the pinned lock set verbatim (stdout) — for sharing / CI.
pub fn freeze() -> Result<()> {
    let env = require_active_env()?;
    let text = std::fs::read_to_string(env.join(LOCK_FILE)).unwrap_or_default();
    print!("{}", text);
    Ok(())
}

// ── lockfile ────────────────────────────────────────────────────────────────

/// Where a LOCKED (installed) package came from — the RESOLVED, pinned source.
///
/// Distinct from `manifest::DepSource`: a manifest's `git:` dependency is an
/// UNRESOLVED URL (possibly with a `@ref`), whereas a lock's git source always
/// carries the exact resolved commit SHA (the pin). A path source stays as-is.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum LockSource {
    /// A local directory (Phase 1). Stored as a canonical absolute path.
    Path(String),
    /// A git remote pinned to an exact commit (Phase 2).
    Git { url: String, commit: String },
}

/// One pinned package in `pyrst.lock`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LockEntry {
    pub name: String,
    pub version: String,
    pub source: LockSource,
}

/// Read `<env>/pyrst.lock` into a name→entry map. A missing lock is an empty map.
pub fn read_lock(env: &Path) -> Result<BTreeMap<String, LockEntry>> {
    let path = env.join(LOCK_FILE);
    let text = match std::fs::read_to_string(&path) {
        Ok(t) => t,
        Err(_) => return Ok(BTreeMap::new()),
    };
    let mut map = BTreeMap::new();
    for line in text.lines() {
        let line = line.trim_end();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let fields: Vec<&str> = line.split('\t').collect();
        // A path entry is 4 fields (`name ver path <abs>`); a git entry is 5
        // (`name ver git <url> <sha>`) — the resolved commit is the pin.
        let malformed = |want: &str| {
            Error::Pkg(format!(
                "{}: malformed lock line (expected {}): {}",
                path.display(),
                want,
                line
            ))
        };
        if fields.len() < 3 {
            return Err(malformed("at least 3 tab-separated fields"));
        }
        let source = match fields[2] {
            "path" => {
                if fields.len() != 4 {
                    return Err(malformed("4 tab-separated fields for a `path` entry"));
                }
                LockSource::Path(fields[3].to_string())
            }
            "git" => {
                if fields.len() != 5 {
                    return Err(malformed("5 tab-separated fields for a `git` entry (name ver git url sha)"));
                }
                LockSource::Git { url: fields[3].to_string(), commit: fields[4].to_string() }
            }
            other => {
                return Err(Error::Pkg(format!(
                    "{}: unknown lock source kind `{}`",
                    path.display(),
                    other
                )))
            }
        };
        map.insert(
            fields[0].to_string(),
            LockEntry {
                name: fields[0].to_string(),
                version: fields[1].to_string(),
                source,
            },
        );
    }
    Ok(map)
}

/// Write the lock deterministically: a fixed header + one tab-separated line per
/// package, SORTED by name (the `BTreeMap` iteration order). No timestamps.
pub fn write_lock(env: &Path, lock: &BTreeMap<String, LockEntry>) -> Result<()> {
    let mut out = String::from(LOCK_HEADER);
    for entry in lock.values() {
        match &entry.source {
            LockSource::Path(p) => out.push_str(&format!(
                "{}\t{}\tpath\t{}\n",
                entry.name, entry.version, p
            )),
            LockSource::Git { url, commit } => out.push_str(&format!(
                "{}\t{}\tgit\t{}\t{}\n",
                entry.name, entry.version, url, commit
            )),
        }
    }
    std::fs::write(env.join(LOCK_FILE), out)?;
    Ok(())
}

// ── `pyrst install` ─────────────────────────────────────────────────────────

/// Install a package (and its transitive deps) into the active env, or — with no
/// argument — reproduce the env from its `pyrst.lock`.
///
/// `spec` is EITHER a git URL (`url`, `url@<ref>`, `url#<sha>` — cloned into the
/// SHA-keyed cache and pinned) OR a local path (Phase-1 copy). `--force` reinstalls
/// over a name/source collision.
pub fn install(spec: Option<String>, force: bool) -> Result<()> {
    let env = require_active_env()?;
    let count = match spec {
        Some(s) if looks_like_git_url(&s) => install_git_root(&env, &s, force)?,
        Some(s) => {
            let path = PathBuf::from(&s);
            let canon = path.canonicalize().map_err(|_| {
                Error::Pkg(format!("install path '{}' does not exist", path.display()))
            })?;
            if force {
                let source = LockSource::Path(canon.to_string_lossy().into_owned());
                install_root(&env, &canon, source, true)?
            } else {
                install_into(&env, &canon)?
            }
        }
        None => reproduce_into(&env)?,
    };
    eprintln!("installed {} package(s) into {}", count, env.display());
    Ok(())
}

/// Heuristic: does `s` name a git remote (vs a local filesystem path)? A remote has
/// a scheme (`https://`, `ssh://`, `file://`, …), or ends in `.git`, or is the
/// scp-short form `user@host:path`. Everything else is treated as a local path
/// (the Phase-1 workflow). The `file://` fixtures the test suite uses classify as
/// git via the `://` scheme.
pub fn looks_like_git_url(s: &str) -> bool {
    if s.contains("://") || s.ends_with(".git") {
        return true;
    }
    // scp form `user@host:path`: an `@` and a `:` before any `/`.
    if let Some(at) = s.find('@') {
        let head = s.split('/').next().unwrap_or(s);
        if head.contains(':') && at < head.len() {
            return true;
        }
    }
    false
}

/// Clone a git package into the SHA-keyed cache and verify it IS a pyrst package
/// (a `pyrst.yaml` at the clone root — the manifest's presence is what certifies
/// it, per §C). An honest, URL-based error otherwise. Memoised per install run: the
/// same spec (a bare-URL diamond's repeat edges) resolves ONCE.
fn clone_git_package(state: &mut InstallState, spec: &str) -> Result<fetch::GitCheckout> {
    if let Some(co) = state.git_memo.get(spec) {
        return Ok(co.clone());
    }
    let co = fetch::resolve_spec(spec)?;
    if !co.dir.join(MANIFEST_FILE).is_file() {
        return Err(Error::Pkg(format!(
            "{} is not a pyrst package (no {} at its root)",
            co.url, MANIFEST_FILE
        )));
    }
    eprintln!("  cloned {} @ {}", co.url, short_sha(&co.commit));
    state.git_memo.insert(spec.to_string(), co.clone());
    Ok(co)
}

/// A short (≤10 hex) commit for human-facing output.
fn short_sha(sha: &str) -> &str {
    &sha[..sha.len().min(10)]
}

/// DFS state carried through a single install run.
struct InstallState {
    /// `<env>/packages`.
    store: PathBuf,
    /// The accumulating lock set (seeded from the existing lock so incremental
    /// installs add to the env, AND so collision detection sees prior installs).
    /// Written back at the end.
    lock: BTreeMap<String, LockEntry>,
    /// Packages fully processed THIS run (copied + recursed) — diamond dedup.
    done: HashSet<String>,
    /// Names currently on the DFS stack — cycle detection.
    stack: Vec<String>,
    /// `--force`: reinstall over a name/source collision instead of erroring.
    force: bool,
    /// Git resolutions already performed THIS run, keyed by the raw dependency spec
    /// (url / `url@ref` / `url#sha`). A bare-URL diamond referenced from N siblings
    /// resolves + clones ONCE — the repeat references hit this memo (no `ls-remote`,
    /// no clone). Cross-run dedup is handled by the on-disk SHA-keyed clone cache.
    git_memo: HashMap<String, fetch::GitCheckout>,
}

/// Seed a fresh install state for `env`: an empty store (created), the existing lock
/// (so incremental installs accumulate and collision detection sees prior installs),
/// and empty visited/stack/memo sets.
fn new_state(env: &Path, force: bool) -> Result<InstallState> {
    let store = env.join(PACKAGES_DIR);
    std::fs::create_dir_all(&store)?;
    Ok(InstallState {
        store,
        lock: read_lock(env)?,
        done: HashSet::new(),
        stack: Vec::new(),
        force,
        git_memo: HashMap::new(),
    })
}

/// Install the package rooted at `pkg_dir` (a LOCAL path) into `env`. Public + its
/// `(env, pkg_dir)` signature preserved for the venv unit tests. Returns the number
/// of packages installed this run.
pub fn install_into(env: &Path, pkg_dir: &Path) -> Result<usize> {
    let source = LockSource::Path(pkg_dir.to_string_lossy().into_owned());
    install_root(env, pkg_dir, source, false)
}

/// Seed the install state and run the DFS from `pkg_dir` (whose resolved lock
/// `source` the caller supplies — a canonical path, or a pinned git url+sha).
fn install_root(env: &Path, pkg_dir: &Path, source: LockSource, force: bool) -> Result<usize> {
    let mut state = new_state(env, force)?;
    install_dfs(&mut state, pkg_dir, None, source)?;
    write_lock(env, &state.lock)?;
    Ok(state.done.len())
}

/// Install a git target (`url`, `url@ref`, or `url#sha`) as the DFS root. The root
/// clone and every transitive git dep share ONE install state (and its git memo), so
/// a bare-URL diamond that reaches the root package again resolves once.
fn install_git_root(env: &Path, spec: &str, force: bool) -> Result<usize> {
    let mut state = new_state(env, force)?;
    let co = clone_git_package(&mut state, spec)?;
    let source = LockSource::Git { url: co.url.clone(), commit: co.commit.clone() };
    install_dfs(&mut state, &co.dir, None, source)?;
    write_lock(env, &state.lock)?;
    Ok(state.done.len())
}

/// Reproduce the env from its lock — a FLAT materialise (NOT the DFS): for each
/// locked package, re-obtain its pinned source (a local path, or a git clone AT THE
/// LOCKED SHA) and copy it into the store. Byte-reproducible: a git package is
/// re-cloned at its exact pinned commit, so re-materialising a lock yields an
/// identical store. (A flat pass is correct because the lock is already the
/// complete, coherent, flattened install set; re-resolving each package's manifest
/// deps would risk re-resolving a BARE dep URL to a newer HEAD, defeating the pin.)
fn reproduce_into(env: &Path) -> Result<usize> {
    let lock = read_lock(env)?;
    if lock.is_empty() {
        return Err(Error::Pkg(format!(
            "nothing to reproduce: {} has no locked packages",
            env.join(LOCK_FILE).display()
        )));
    }
    let store = env.join(PACKAGES_DIR);
    std::fs::create_dir_all(&store)?;
    let mut count = 0usize;
    for entry in lock.values() {
        let src_dir = match &entry.source {
            LockSource::Path(p) => PathBuf::from(p).canonicalize().map_err(|_| {
                Error::Pkg(format!(
                    "locked path '{}' for package `{}` no longer exists",
                    p, entry.name
                ))
            })?,
            LockSource::Git { url, commit } => {
                let co = fetch::resolve(url, &fetch::RefSpec::Commit(commit.clone()))?;
                if !co.dir.join(MANIFEST_FILE).is_file() {
                    return Err(Error::Pkg(format!(
                        "{} (commit {}) is not a pyrst package (no {} at its root)",
                        url, commit, MANIFEST_FILE
                    )));
                }
                eprintln!("  cloned {} @ {}", url, short_sha(commit));
                co.dir
            }
        };
        // Honesty: the materialised source must be the package the lock names.
        let manifest = Manifest::load(&src_dir)?;
        if manifest.name != entry.name {
            return Err(Error::Pkg(format!(
                "lock names package `{}` but the source at {} is named `{}`",
                entry.name,
                src_dir.display(),
                manifest.name
            )));
        }
        copy_package(&src_dir, &store.join(&entry.name))?;
        count += 1;
    }
    Ok(count)
}

/// The install DFS body for one package directory. `pkg_dir` MUST be canonical (a
/// local path, or a git clone dir). `expected_name`, when set, is the dependency
/// name the parent declared. `source` is how this package is pinned in the lock.
fn install_dfs(
    state: &mut InstallState,
    pkg_dir: &Path,
    expected_name: Option<&str>,
    source: LockSource,
) -> Result<()> {
    let manifest = Manifest::load(pkg_dir)?;
    let name = manifest.name.clone();

    if let Some(exp) = expected_name {
        if exp != name {
            return Err(Error::Pkg(format!(
                "dependency was declared as `{}` but the package at {} is named `{}`",
                exp,
                pkg_dir.display(),
                name
            )));
        }
    }

    // Cycle: the package is already on the current DFS stack.
    if let Some(pos) = state.stack.iter().position(|n| n == &name) {
        let mut cycle: Vec<String> = state.stack[pos..].to_vec();
        cycle.push(name.clone());
        return Err(Error::Pkg(format!(
            "dependency cycle detected: {}",
            cycle.join(" → ")
        )));
    }

    // Collision — the same name already pinned (this run or a prior install) from a
    // GENUINELY DIFFERENT source. The lock is seeded from the existing lock and
    // updated as we install, so it captures both. Same source → not a conflict
    // (idempotent). `--force` overrides. Checked BEFORE the diamond short-circuit
    // so a differing source is never silently absorbed as a diamond.
    if !state.force {
        if let Some(entry) = state.lock.get(&name) {
            if sources_conflict(&entry.source, &source) {
                let prev = entry.source.clone();
                return Err(collision_err(&name, &prev, &source));
            }
        }
    }

    // Diamond: already fully installed this run (same source) — nothing to do.
    if state.done.contains(&name) {
        return Ok(());
    }

    // Copy the package (manifest + its `.pyrs` tree) into the store.
    copy_package(pkg_dir, &state.store.join(&name))?;

    // Pin it in the lock (before recursing, so an in-progress package is visible to
    // the collision check and a cycle is still caught by the stack).
    state.lock.insert(
        name.clone(),
        LockEntry {
            name: name.clone(),
            version: manifest.version.clone(),
            source,
        },
    );

    // Recurse into declared dependencies. A `path:` dep resolves relative to THIS
    // package's dir; a `git:` dep is cloned into the SHA-keyed cache and pinned —
    // reusing the very same DFS (visited-set, diamond dedup, cycle detection).
    state.stack.push(name.clone());
    for dep in &manifest.dependencies {
        let (dep_dir, dep_source) = match &dep.source {
            DepSource::Path(p) => {
                let joined = pkg_dir.join(p);
                let canon = joined.canonicalize().map_err(|_| {
                    Error::Pkg(format!(
                        "package `{}` declares dependency `{}` at path `{}`, which does not exist",
                        name, dep.name, p
                    ))
                })?;
                let src = LockSource::Path(canon.to_string_lossy().into_owned());
                (canon, src)
            }
            DepSource::Git(url) => {
                let co = clone_git_package(state, url)?;
                let src = LockSource::Git { url: co.url.clone(), commit: co.commit.clone() };
                (co.dir, src)
            }
        };
        install_dfs(state, &dep_dir, Some(&dep.name), dep_source)?;
    }
    state.stack.pop();
    state.done.insert(name);
    Ok(())
}

/// Do two lock sources refer to genuinely DIFFERENT origins (a real name
/// collision)? Same path (canonicalised) or same git url+sha → not a conflict
/// (idempotent re-install); a path-vs-git kind mismatch always is.
fn sources_conflict(a: &LockSource, b: &LockSource) -> bool {
    match (a, b) {
        (LockSource::Path(pa), LockSource::Path(pb)) => {
            match (PathBuf::from(pa).canonicalize(), PathBuf::from(pb).canonicalize()) {
                (Ok(x), Ok(y)) => x != y,
                _ => pa != pb,
            }
        }
        (
            LockSource::Git { url: u1, commit: c1 },
            LockSource::Git { url: u2, commit: c2 },
        ) => u1 != u2 || c1 != c2,
        _ => true,
    }
}

fn describe_source(s: &LockSource) -> String {
    match s {
        LockSource::Path(p) => p.clone(),
        LockSource::Git { url, commit } => format!("{} @ {}", url, short_sha(commit)),
    }
}

fn collision_err(name: &str, prev: &LockSource, current: &LockSource) -> Error {
    Error::Pkg(format!(
        "package name collision: `{}` is already installed from {} but is now requested from {} — \
         two different sources cannot share one env name (use --force to reinstall)",
        name,
        describe_source(prev),
        describe_source(current)
    ))
}

/// Copy a package into `dst`: the manifest + every `.pyrs` under `src_root`
/// (recursively, structure-preserving). `dst` is removed first so a re-install is
/// a deterministic fresh copy. Non-`.pyrs` files (READMEs, test oracles, compiled
/// demos) are NOT copied — only the manifest and the importable source. Any extra
/// `.pyrs` that is never imported is inert (the resolver only parses a module when
/// something imports it), so copying the whole `.pyrs` tree is safe and supports
/// nested-module packages.
fn copy_package(src_root: &Path, dst: &Path) -> Result<()> {
    if dst.exists() {
        std::fs::remove_dir_all(dst)?;
    }
    std::fs::create_dir_all(dst)?;
    std::fs::copy(src_root.join(MANIFEST_FILE), dst.join(MANIFEST_FILE)).map_err(|e| {
        Error::Pkg(format!(
            "failed to copy manifest from {}: {}",
            src_root.display(),
            e
        ))
    })?;
    copy_pyrs_tree(src_root, src_root, dst)
}

/// Recursively copy every `*.pyrs` file under `dir`, replicating its path relative
/// to `root` beneath `dst`. Directory entries are visited in sorted order for
/// deterministic behaviour.
fn copy_pyrs_tree(root: &Path, dir: &Path, dst: &Path) -> Result<()> {
    let mut entries: Vec<PathBuf> = std::fs::read_dir(dir)?
        .flatten()
        .map(|e| e.path())
        .collect();
    entries.sort();
    for path in entries {
        if path.is_dir() {
            // Skip dot-directories (e.g. a clone's `.git/`). They never hold a
            // package's importable `.pyrs` modules, so walking them is pure overhead
            // now that every git source is a real clone. The store stays byte-for-byte
            // identical (only `.pyrs` are ever copied), just cheaper to produce.
            if is_hidden_dir(&path) {
                continue;
            }
            copy_pyrs_tree(root, &path, dst)?;
        } else if path.extension().and_then(|s| s.to_str()) == Some("pyrs") {
            let rel = path.strip_prefix(root).unwrap_or(&path);
            let target = dst.join(rel);
            if let Some(parent) = target.parent() {
                std::fs::create_dir_all(parent)?;
            }
            std::fs::copy(&path, &target)?;
        }
    }
    Ok(())
}

/// A directory whose name begins with `.` (e.g. a clone's `.git/`) — never part of a
/// package's importable source, so it is skipped when copying into the store.
fn is_hidden_dir(path: &Path) -> bool {
    path.file_name()
        .and_then(|s| s.to_str())
        .map(|n| n.starts_with('.'))
        .unwrap_or(false)
}

// ── §F env-completeness gate (driver-side) ──────────────────────────────────

/// From the resolved modules' canonical source paths, collect the set of env
/// PACKAGE names the build actually used — i.e. modules whose source lives under
/// `<env>/packages/<name>/`. Modules from the entry program's own tree or the
/// embedded stdlib are excluded (their paths are not under the store).
pub fn used_env_packages(env: &Path, source_paths: &[&Path]) -> BTreeSet<String> {
    let store = env.join(PACKAGES_DIR);
    let store = store.canonicalize().unwrap_or(store);
    let mut used = BTreeSet::new();
    for sp in source_paths {
        if let Ok(rel) = sp.strip_prefix(&store) {
            if let Some(first) = rel.components().next() {
                used.insert(first.as_os_str().to_string_lossy().into_owned());
            }
        }
    }
    used
}

/// (§F) Confirm the env is COMPLETE for the packages the build uses: every used
/// package's manifest-declared dependencies must ALSO be installed in the store.
/// An incomplete env is an honest error naming exactly what to install, raised
/// BEFORE codegen. (Most missing-package cases are already caught earlier by the
/// resolver's env-aware `PackageNotInstalled`; this adds the manifest-coherence
/// guarantee that the env is self-consistent.)
pub fn check_env_completeness(env: &Path, used: &BTreeSet<String>) -> Result<()> {
    let store = env.join(PACKAGES_DIR);
    for pkg in used {
        let manifest = match Manifest::load(&store.join(pkg)) {
            Ok(m) => m,
            // A used package with no readable manifest in the store should not
            // happen (install copies it); stay lenient rather than fabricate.
            Err(_) => continue,
        };
        for dep in &manifest.dependencies {
            if !store.join(&dep.name).is_dir() {
                return Err(Error::Pkg(format!(
                    "the active environment '{}' is incomplete: package `{}` depends on `{}`, \
                     which is not installed — `pyrst install` it",
                    env.display(),
                    pkg,
                    dep.name
                )));
            }
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A unique temp directory for a test fixture.
    fn temp_dir(tag: &str) -> PathBuf {
        let d = std::env::temp_dir().join(format!(
            "pyrst-venv-test-{}-{}-{}",
            tag,
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        std::fs::create_dir_all(&d).unwrap();
        d
    }

    /// Author a minimal package directory: `pyrst.yaml` + a trivial module.
    fn write_pkg(dir: &Path, name: &str, deps: &[(&str, &str)]) {
        std::fs::create_dir_all(dir).unwrap();
        let mut man = format!("name: {}\nversion: 0.1.0\npackage_root: .\n", name);
        if deps.is_empty() {
            man.push_str("dependencies: []\n");
        } else {
            man.push_str("dependencies:\n");
            for (dname, dpath) in deps {
                man.push_str(&format!("  - name: {}\n    path: {}\n", dname, dpath));
            }
        }
        std::fs::write(dir.join(MANIFEST_FILE), man).unwrap();
        std::fs::write(dir.join(format!("{}.pyrs", name)), "def ping() -> int:\n    return 1\n").unwrap();
    }

    /// A ready-to-use empty env directory (marker + empty store + empty lock).
    fn make_env(dir: &Path) -> PathBuf {
        let env = dir.join(".pyrstenv");
        std::fs::create_dir_all(env.join(PACKAGES_DIR)).unwrap();
        std::fs::write(env.join(ENV_META_FILE), "pyrst_version: test\n").unwrap();
        std::fs::write(env.join(LOCK_FILE), LOCK_HEADER).unwrap();
        env
    }

    /// `pyrst venv` writes activation scripts for every shell (bash/zsh, Windows
    /// cmd, PowerShell) so an env is cross-platform (card 12a7a021).
    #[test]
    fn venv_writes_cross_platform_activation_scripts() {
        let base = temp_dir("activate-scripts");
        let env = base.join(".pyrstenv");
        create(Some(env.clone())).expect("create env");
        let bash = std::fs::read_to_string(env.join("activate")).unwrap();
        let bat = std::fs::read_to_string(env.join("activate.bat")).unwrap();
        let deact = std::fs::read_to_string(env.join("deactivate.bat")).unwrap();
        let ps1 = std::fs::read_to_string(env.join("Activate.ps1")).unwrap();
        // POSIX: exports PYRST_VENV + defines deactivate + a green (label) prompt.
        assert!(bash.contains("export PYRST_VENV"));
        assert!(bash.contains("deactivate()"));
        assert!(bash.contains("_OLD_PYRST_PS1"), "must save the old prompt");
        assert!(bash.contains("\\033[32m"), "bash: green via ANSI");
        assert!(bash.contains("ZSH_VERSION") && bash.contains("%F{green}"), "zsh: green via %F");
        assert!(bash.contains("(.pyrstenv)"), "prompt shows the env basename");
        assert!(bash.contains("PYRST_VENV='"), "path must be single-quoted (no injection)");
        // cmd: sets PYRST_VENV, saves the old value, adds the env to PATH so
        // `deactivate` is callable by name, colours the prompt, CRLF endings.
        assert!(bat.contains("set \"PYRST_VENV="));
        assert!(bat.contains("set \"_OLD_PYRST_VENV=%PYRST_VENV%\""));
        assert!(bat.contains("set \"PATH="), "must put the env dir on PATH");
        assert!(bat.contains("$E[32m(.pyrstenv)$E[0m"), "green prompt prefix");
        assert!(bat.contains("\r\n"), "activate.bat must use CRLF for cmd");
        // deactivate.bat restores PYRST_VENV, PATH, and PROMPT.
        assert!(deact.contains("set \"PYRST_VENV=%_OLD_PYRST_VENV%\""));
        assert!(deact.contains("set \"PATH=%_OLD_PYRST_PATH%\""));
        assert!(deact.contains("set \"PROMPT=%_OLD_PYRST_PROMPT%\""));
        // PowerShell: sets $env:PYRST_VENV, a green prompt fn, + a deactivate fn.
        assert!(ps1.contains("$env:PYRST_VENV = '"), "path must be a single-quoted literal");
        assert!(ps1.contains("function global:prompt"));
        assert!(ps1.contains("-ForegroundColor Green"));
        assert!(ps1.contains("(.pyrstenv)"));
        assert!(ps1.contains("function global:deactivate"));
        let _ = std::fs::remove_dir_all(&base);
    }

    /// The prompt label is sanitised: normal names pass through, shell/prompt
    /// metacharacters are neutralised so a crafted env name can't inject into PS1.
    #[test]
    fn env_label_sanitises_metacharacters() {
        assert_eq!(env_label(Path::new("/x/.pyrstenv")), ".pyrstenv");
        assert_eq!(env_label(Path::new("/x/my-env_3.11+rc")), "my-env_3.11+rc");
        // `$ ( ) space ~` → `_`, while `-` is allowed (a normal name char).
        assert_eq!(env_label(Path::new("/x/$(rm -rf ~)")), "__rm_-rf___");
        assert_eq!(env_label(Path::new("/x/`id`")), "_id_");
        // No usable component → the constant fallback.
        assert_eq!(env_label(Path::new("/")), "pyrstenv");
    }

    /// The per-shell quoting helpers neutralise injection, and the embedded env path
    /// is single-quoted in the generated scripts (not the old unsafe `"…"` form).
    #[test]
    fn quote_helpers_neutralise_injection() {
        // POSIX single-quote: `'` → `'\''`, everything else literal.
        assert_eq!(posix_squote("/a/b"), "'/a/b'");
        assert_eq!(posix_squote("a'b"), "'a'\\''b'");
        assert_eq!(posix_squote("x$(id)`id`\""), "'x$(id)`id`\"'");
        // PowerShell single-quote: `'` doubled.
        assert_eq!(ps_squote("/a/b"), "'/a/b'");
        assert_eq!(ps_squote("a'b"), "'a''b'");
        // cmd: `%` doubled so cmd can't expand %NAME% at parse time.
        assert_eq!(cmd_escape("a%PATH%b"), "a%%PATH%%b");
        assert_eq!(cmd_escape("/plain/path"), "/plain/path");
        // A hostile env path lands inside single quotes in the bash script, so the
        // `$(...)` never executes when the user sources `activate`.
        let evil = Path::new("/tmp/x$(touch pwned)/.pyrstenv");
        let bash = activate_script(evil);
        assert!(bash.contains("PYRST_VENV='/tmp/x$(touch pwned)/.pyrstenv'"));
        // The literal path must never appear in a double-quoted context (where `$(...)`
        // would execute). It appears exactly once, single-quoted, above.
        assert!(!bash.contains("\"/tmp/x$(touch pwned)"), "path must not be double-quoted");
        let ps1 = activate_ps1(evil);
        assert!(ps1.contains("$env:PYRST_VENV = '/tmp/x$(touch pwned)/.pyrstenv'"));
    }

    /// Discovery: an explicit, valid PYRST_VENV wins over auto-detect.
    #[test]
    fn discovery_explicit_pyrst_venv_wins() {
        let base = temp_dir("disc-explicit");
        let env = make_env(&base);
        // Even with a `.pyrstenv` also present in cwd, the explicit path is used.
        let got = discover_env_from(Some(&env), &base).expect("explicit env resolves");
        assert_eq!(got, env.canonicalize().unwrap());
        let _ = std::fs::remove_dir_all(&base);
    }

    /// Discovery: with no PYRST_VENV, a `.pyrstenv/` is auto-detected by walking
    /// cwd→ancestors (found from a nested subdirectory).
    #[test]
    fn discovery_auto_detect_walks_ancestors() {
        let base = temp_dir("disc-auto");
        let env = make_env(&base);
        let nested = base.join("a").join("b");
        std::fs::create_dir_all(&nested).unwrap();
        let got = discover_env_from(None, &nested).expect("auto-detect finds the ancestor env");
        assert_eq!(got, env.canonicalize().unwrap());
        let _ = std::fs::remove_dir_all(&base);
    }

    /// Discovery: neither PYRST_VENV nor a `.pyrstenv/` → None (the no-env path).
    #[test]
    fn discovery_none_when_absent() {
        let base = temp_dir("disc-none");
        assert!(discover_env_from(None, &base).is_none());
        // A PYRST_VENV pointing at a non-env directory also yields None.
        assert!(discover_env_from(Some(&base), &base).is_none());
        let _ = std::fs::remove_dir_all(&base);
    }

    /// (card 587a9dcb) Anchored discovery: an explicit, valid PYRST_VENV wins over
    /// BOTH the anchor walk and the CWD walk.
    #[test]
    fn discovery_anchored_explicit_pyrst_venv_wins() {
        let base = temp_dir("disc-anch-explicit");
        // An explicit env, plus DIFFERENT `.pyrstenv`s at the anchor and the cwd —
        // the explicit one must still win.
        let explicit = make_env(&base.join("explicit"));
        let anchor_base = base.join("anchor");
        let _anchor_env = make_env(&anchor_base);
        let cwd_base = base.join("cwd");
        let _cwd_env = make_env(&cwd_base);
        let got = discover_env_anchored(Some(&explicit), &anchor_base, &cwd_base)
            .expect("explicit env resolves");
        assert_eq!(got, explicit.canonicalize().unwrap());
        let _ = std::fs::remove_dir_all(&base);
    }

    /// (card 587a9dcb) Anchored discovery: with no PYRST_VENV, the ANCHOR's
    /// `.pyrstenv/` is found by walking anchor→ancestors even when the CWD is an
    /// UNRELATED directory with no env — the VSCode/`pyrst check <abs path>` fix.
    #[test]
    fn discovery_anchored_walks_anchor_when_cwd_elsewhere() {
        let base = temp_dir("disc-anch-anchor");
        let proj = base.join("proj");
        let env = make_env(&proj);
        // The anchor is a nested subdir of the project (the file's dir); the CWD is
        // an unrelated env-less directory.
        let anchor = proj.join("src").join("pkg");
        std::fs::create_dir_all(&anchor).unwrap();
        let cwd = temp_dir("disc-anch-anchor-cwd");
        let got = discover_env_anchored(None, &anchor, &cwd)
            .expect("anchor-walk finds the project env regardless of cwd");
        assert_eq!(got, env.canonicalize().unwrap());
        let _ = std::fs::remove_dir_all(&base);
        let _ = std::fs::remove_dir_all(&cwd);
    }

    /// (card 587a9dcb) Anchored discovery: when the ANCHOR has no `.pyrstenv/`
    /// ancestor, discovery falls back to the CWD walk — this is what keeps the REPL
    /// working (its temp file has no env ancestor, so it resolves the project the
    /// user launched `repl` from).
    #[test]
    fn discovery_anchored_cwd_fallback_when_anchor_has_none() {
        let base = temp_dir("disc-anch-cwd");
        // The anchor (a stand-in for a /tmp REPL temp file's dir) has no env.
        let anchor = temp_dir("disc-anch-cwd-anchor");
        // The cwd is inside the project env.
        let proj = base.join("proj");
        let env = make_env(&proj);
        let cwd = proj.join("nested");
        std::fs::create_dir_all(&cwd).unwrap();
        let got = discover_env_anchored(None, &anchor, &cwd)
            .expect("cwd-walk fallback finds the project env when the anchor has none");
        assert_eq!(got, env.canonicalize().unwrap());
        let _ = std::fs::remove_dir_all(&base);
        let _ = std::fs::remove_dir_all(&anchor);
    }

    /// (card 587a9dcb) Anchored discovery: neither the anchor nor the CWD has a
    /// `.pyrstenv/` ancestor and PYRST_VENV is unset → None (the byte-unchanged
    /// no-env path — the invariant the repo tree relies on).
    #[test]
    fn discovery_anchored_none_when_neither() {
        let anchor = temp_dir("disc-anch-none-anchor");
        let cwd = temp_dir("disc-anch-none-cwd");
        assert!(discover_env_anchored(None, &anchor, &cwd).is_none());
        // An invalid explicit PYRST_VENV also yields None (falls through, no env).
        assert!(discover_env_anchored(Some(&anchor), &anchor, &cwd).is_none());
        let _ = std::fs::remove_dir_all(&anchor);
        let _ = std::fs::remove_dir_all(&cwd);
    }

    /// (card 587a9dcb, SECURITY) A `.pyrstenv` whose PARENT is world-writable (the
    /// shared-temp-root attack shape) is REFUSED by the anchor walk — the compiler
    /// falls back to the CWD env instead of silently activating an attacker-plantable
    /// env. This is what closes the REPL's `/tmp`-anchored code-execution vector.
    #[cfg(unix)]
    #[test]
    fn discovery_refuses_world_writable_env_dir() {
        use std::os::unix::fs::PermissionsExt;
        let base = temp_dir("disc-ww");
        // A world-writable "shared temp"-like dir holding a PLANTED env.
        let shared = base.join("shared");
        let _planted = make_env(&shared); // shared/.pyrstenv
        std::fs::set_permissions(&shared, std::fs::Permissions::from_mode(0o1777)).unwrap();
        assert!(dir_is_world_writable(&shared), "precondition: parent is world-writable");
        // A clean, user-owned CWD with its own env.
        let cwd_base = base.join("cwd");
        let cwd_env = make_env(&cwd_base);
        // Anchored on the world-writable dir → its planted env is skipped; CWD wins.
        assert_eq!(
            discover_env_anchored(None, &shared, &cwd_base),
            Some(cwd_env.canonicalize().unwrap()),
            "must refuse the world-writable env and fall back to CWD",
        );
        // With no CWD env either, the planted env is NEVER honored → None.
        let empty_cwd = temp_dir("disc-ww-empty");
        assert!(discover_env_anchored(None, &shared, &empty_cwd).is_none());
        let _ = std::fs::remove_dir_all(&base);
        let _ = std::fs::remove_dir_all(&empty_cwd);
    }

    /// Lockfile round-trip: write then read yields the same map, sorted + pinned.
    #[test]
    fn lockfile_round_trips() {
        let base = temp_dir("lock");
        let env = make_env(&base);
        let mut lock = BTreeMap::new();
        lock.insert(
            "numpyrs".to_string(),
            LockEntry { name: "numpyrs".into(), version: "0.1.0".into(), source: LockSource::Path("/abs/numpyrs".into()) },
        );
        lock.insert(
            "tzdata".to_string(),
            LockEntry { name: "tzdata".into(), version: "0.2.1".into(), source: LockSource::Path("/abs/tzdata".into()) },
        );
        // A git-sourced entry pins the resolved commit SHA (5-field line).
        lock.insert(
            "dateutil".to_string(),
            LockEntry {
                name: "dateutil".into(),
                version: "0.3.0".into(),
                source: LockSource::Git {
                    url: "https://github.com/Elouderb/dateutil".into(),
                    commit: "d3543dfe79920046e4b281b377af14bbd2026be2".into(),
                },
            },
        );
        write_lock(&env, &lock).unwrap();
        let back = read_lock(&env).unwrap();
        assert_eq!(back, lock, "lock must round-trip exactly (path + git)");
        let _ = std::fs::remove_dir_all(&base);
    }

    /// URL-vs-path classification: git remotes are detected; local paths are not.
    #[test]
    fn git_url_detection() {
        assert!(looks_like_git_url("https://github.com/Elouderb/numpyrs"));
        assert!(looks_like_git_url("file:///tmp/x/repo"));
        assert!(looks_like_git_url("git@github.com:Elouderb/numpyrs.git"));
        assert!(looks_like_git_url("ssh://git@host/owner/repo"));
        assert!(looks_like_git_url("https://github.com/Elouderb/numpyrs@v0.2.0"));
        assert!(!looks_like_git_url("../numpyrs"));
        assert!(!looks_like_git_url("/abs/path/to/pkg"));
        assert!(!looks_like_git_url("extern/packages/kodiak"));
    }

    /// Transitive install + diamond dedup: kodiak→{numpyrs, dateutil, tzdata},
    /// dateutil→tzdata. tzdata (the diamond point) is installed exactly once, and
    /// the lock pins all four.
    #[test]
    fn install_transitive_with_diamond() {
        let base = temp_dir("install-diamond");
        let env = make_env(&base);
        let pkgs = base.join("src");
        write_pkg(&pkgs.join("tzdata"), "tzdata", &[]);
        write_pkg(&pkgs.join("numpyrs"), "numpyrs", &[]);
        write_pkg(&pkgs.join("dateutil"), "dateutil", &[("tzdata", "../tzdata")]);
        write_pkg(
            &pkgs.join("kodiak"),
            "kodiak",
            &[("numpyrs", "../numpyrs"), ("dateutil", "../dateutil"), ("tzdata", "../tzdata")],
        );

        let count = install_into(&env, &pkgs.join("kodiak")).expect("transitive install succeeds");
        assert_eq!(count, 4, "kodiak + its 3 transitive deps install once each (tzdata deduped)");

        let store = env.join(PACKAGES_DIR);
        for p in ["kodiak", "numpyrs", "dateutil", "tzdata"] {
            assert!(store.join(p).join(MANIFEST_FILE).is_file(), "{p} manifest is in the store");
            assert!(store.join(p).join(format!("{p}.pyrs")).is_file(), "{p} module copied");
        }
        let lock = read_lock(&env).unwrap();
        assert_eq!(lock.len(), 4, "lock pins all four packages");

        // Completeness passes for this coherent env.
        let used: BTreeSet<String> = ["kodiak", "numpyrs", "dateutil", "tzdata"].iter().map(|s| s.to_string()).collect();
        check_env_completeness(&env, &used).expect("a fully-installed env is complete");

        let _ = std::fs::remove_dir_all(&base);
    }

    /// Cycle detection: a→b→a is an honest error naming the cycle.
    #[test]
    fn install_cycle_is_honest_error() {
        let base = temp_dir("install-cycle");
        let env = make_env(&base);
        let pkgs = base.join("src");
        write_pkg(&pkgs.join("a"), "a", &[("b", "../b")]);
        write_pkg(&pkgs.join("b"), "b", &[("a", "../a")]);

        let err = install_into(&env, &pkgs.join("a")).unwrap_err().to_string();
        assert!(err.contains("dependency cycle detected"), "got: {err}");
        assert!(err.contains('a') && err.contains('b'), "cycle must name the packages: {err}");
        let _ = std::fs::remove_dir_all(&base);
    }

    /// Completeness: a package that declares a dep which is NOT installed is an
    /// honest incomplete-env error (simulated by installing dateutil→tzdata but
    /// then removing tzdata from the store).
    #[test]
    fn incomplete_env_is_honest_error() {
        let base = temp_dir("incomplete");
        let env = make_env(&base);
        let pkgs = base.join("src");
        write_pkg(&pkgs.join("tzdata"), "tzdata", &[]);
        write_pkg(&pkgs.join("dateutil"), "dateutil", &[("tzdata", "../tzdata")]);
        install_into(&env, &pkgs.join("dateutil")).expect("install");

        // Remove tzdata from the store to make the env incomplete.
        std::fs::remove_dir_all(env.join(PACKAGES_DIR).join("tzdata")).unwrap();

        let used: BTreeSet<String> = ["dateutil"].iter().map(|s| s.to_string()).collect();
        let err = check_env_completeness(&env, &used).unwrap_err().to_string();
        assert!(err.contains("incomplete"), "got: {err}");
        assert!(err.contains("dateutil") && err.contains("tzdata"), "must name the package + missing dep: {err}");
        let _ = std::fs::remove_dir_all(&base);
    }

    /// The dot-directory skip predicate (NIT #2): `.git` and friends are hidden.
    #[test]
    fn is_hidden_dir_flags_dot_directories() {
        assert!(is_hidden_dir(Path::new("/x/.git")));
        assert!(is_hidden_dir(Path::new(".hidden")));
        assert!(!is_hidden_dir(Path::new("/x/src")));
        assert!(!is_hidden_dir(Path::new("frame")));
    }

    /// `pyrst list` source annotation: git → short-sha, path → the dir.
    #[test]
    fn source_label_renders_git_and_path() {
        let g = source_label(&LockSource::Git {
            url: "https://h/o/r".into(),
            commit: "d3543dfe79920046e4b281b377af14bbd2026be2".into(),
        });
        assert_eq!(g, "  (git d3543dfe79)");
        let p = source_label(&LockSource::Path("/abs/pkg".into()));
        assert_eq!(p, "  (path /abs/pkg)");
    }

    /// NIT #2: a `.git` (or any dot-dir) in the source is NOT copied into the store,
    /// while a legitimate nested `.pyrs` module IS.
    #[test]
    fn copy_skips_dot_dirs_but_keeps_nested_modules() {
        let base = temp_dir("copy-skip-dotdir");
        let env = make_env(&base);
        let src = base.join("src").join("pkg");
        write_pkg(&src, "pkg", &[]);
        // A fake `.git` with a `.pyrs` inside — must NOT leak into the store.
        std::fs::create_dir_all(src.join(".git").join("objects")).unwrap();
        std::fs::write(src.join(".git").join("config.pyrs"), "x").unwrap();
        // A real nested module — must be copied.
        std::fs::create_dir_all(src.join("sub")).unwrap();
        std::fs::write(src.join("sub").join("mod.pyrs"), "def f() -> int:\n    return 2\n").unwrap();

        install_into(&env, &src).expect("install");
        let dst = env.join(PACKAGES_DIR).join("pkg");
        assert!(!dst.join(".git").exists(), ".git must not leak into the store");
        assert!(dst.join("sub").join("mod.pyrs").is_file(), "nested module copied");
        assert!(dst.join("pkg.pyrs").is_file(), "top module copied");
        let _ = std::fs::remove_dir_all(&base);
    }
}
